config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

   
  resources :shows
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/show.rb
class Show < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :shows
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[ show edit update destroy ]

  # GET /shows or /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1 or /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to show_url(@show), notice: "Show was successfully created." }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to show_url(@show), notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:name, :genre, :language, :rating, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

    <%= link_to "TV Shows App", root_path, class:"navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
       
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Shows", shows_path, class: "nav-link"%>
          </li>
          
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item">
                <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
              </li>

              <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%>
              </li>
          </ul>
        </li>

        <% else %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Create an Account
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link"%>
            </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>TV Show Ratings</h1>
<p>Keep track of all the shows you have ever watched for future recommendations!</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  <%# bootstrap = https://getbootstrap.com/docs/5.3/getting-started/introduction/ %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TV Shows Ratings</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

  <%=render 'home/header'%>
  <br>
  <div class="container">
    <% if notice %>
     <%= render 'layouts/alerts'%>
    <%end%>
    <br>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">   
    <%= form.text_field :name, placeholder:"Name", class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :genre, placeholder:"Genre", class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.text_field :language, placeholder:"Language", class:"form-control" %>
  </div>
  <div class="mb-3">
    <%= form.number_field :rating, placeholder:"Rating", class:"form-control" %>
  </div>
  
  <%# for testing purposes
  <div class="mb-3">
    <%= form.label :user_id, "Select User" %>
  <%#  <%= form.collection_select :user_id, User.all, :id, :email, { prompt: "Select user" }, class: "form-control" %> 

  <div class="mb-3">
    <%= form.number_field :user_id, id: :show_user_id, type: :hidden, value: current_user&.id, class: "form-control" %> <%# this line creates an id for each user to associate it to its own created list%>
  </div>

  <div class="mb-3"> 
    <%= form.submit class: "btn btn-sm btn-success"%>
  </div>
<% end %>

app/views/shows/_show.html.erb
<%#inside the display for tv shows%>
<table class="table table-bordered"> 
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Language</th>
      <th>Rating</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= show.name %></td>
      <td><%= show.genre %></td>
      <td><%= show.language %></td>
      <td><%= show.rating %></td>
      <td>
      <div class="btn-group" role="group">
        <%= link_to "Edit", edit_show_path(show), class: "btn btn-primary btn-sm" %>
        <%= button_to 'Delete', @show, method: :delete, class: "btn btn-sm btn-danger" %>
      </div>
      </td>
    </tr>
  </tbody>
</table>

app/views/shows/edit.html.erb
<h1>Editing TV Show</h1>
<br>
<%= render "form", show: @show %>

<div>
  <%= link_to "Return", shows_path, class:"btn btn-sm btn-primary" %>
</div>

app/views/shows/index.html.erb
<h1>TV Shows</h1>
<br>
<table class="table table-striped table-bordered">
  <thead class= "table-dark">
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Language</th>
      <th>Rating</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @shows.each do |show| %>
      <% if show.user == current_user %> <%# this if statement allows only the current user logged in to view its own created list %>
      <tr>
        <td><%= show.name %></td>
        <td><%= show.genre %></td>
        <td><%= show.language %></td>
        <td><%= show.rating %></td>
        <td>
          <div class="btn-group" role="group">
            <%= link_to "Display", show, class: "btn btn-primary btn-sm" %> 
            <%= button_to 'Delete', show, method: :delete, class: "btn btn-danger btn-sm" %>
          </div>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "New TV Show", new_show_path, class: "btn btn-sm btn-success" %>

app/views/shows/new.html.erb
<h1>Add a new TV Show</h1>
<br>
<%= render "form", show: @show %>

<div>
  <%= link_to "Back to TV Shows", shows_path, class:"btn btn-sm btn-primary"%>
</div>

app/views/shows/show.html.erb
<%= render @show, class:"table table-striped table-bordered" %>

<div>
  <%= link_to "Return", shows_path, class:"btn btn-sm btn-success" %>
</div>